apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: microcks
spec:
  # Run every minute
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: gp-portal-microcks-integration
            image: duncandoyle/gp-portal-microcks-integration:1.0.0
            imagePullPolicy: Always
            env:
            - name: GP_PORTAL_SERVER_ENDPOINT
              value: "http://developer.example.com/v1"
            - name: MICROCKS_API_SERVER_ENDPOINT
              value: "https://microcks.example.com/api"
            - name: MICROCKS_TOKEN_ENDPOINT
              value: "https://mc-keycloak.example.com/realms/microcks/protocol/openid-connect/token"
            - name: MICROCKS_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: microcks-secret
                  key: MICROCKS_CLIENT_ID
            - name: MICROCKS_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: microcks-secret
                  key: MICROCKS_CLIENT_SECRET
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: SKIP_TLS_VERIFY
              value: "true"
          restartPolicy: OnFailure